// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using GroupExperiment.Modules;
using UIKit;

namespace GroupExperiment
{
	public partial class CreateGroupController : UIViewController
	{
        MyAlerts alerter = new MyAlerts();
        string groupName;

        List<BeneficiaryGroup> beneficiaryGroups;

        public CreateGroupController (IntPtr handle) : base (handle)
		{
            beneficiaryGroups = new List<BeneficiaryGroup>();
            beneficiaryGroups.Add (new BeneficiaryGroup("My guys"));
		}
        
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            NavigationController.NavigationBarHidden = false;
            Title = "Groups";

            groupsTable.Source = new GroupsTableSource(beneficiaryGroups);

            createGroupBtn.TouchUpInside += CreateGroupBtn_TouchUpInside;
        }

        private void CreateGroupBtn_TouchUpInside(object sender, EventArgs e)
        {
            alerter.ShowAlertWithTextField("Create new group", "Enter group name", this, (UIAlertAction obj) =>
            {
                if (String.IsNullOrWhiteSpace(alerter.alertController.TextFields[0].Text))
                {
                    alerter.ShowSimpleAlert("Empty fields", "Group name cannot be empty", this);
                }
                else
                {
                    groupName = alerter.alertController.TextFields[0].Text;
                    Console.WriteLine(groupName);

                    PerformSegue("toGroupController", null);
                }
            });
        }

        public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            if(segue.Identifier == "toGroupController")
            {
                var groupPage = segue.DestinationViewController as GroupController;
                if(groupPage != null)
                {
                    groupPage.groupName = groupName;
                }
            }
        }
    }
}
