// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Net.Http;
using System.Threading.Tasks;
using Foundation;
using GroupExperiment.Modules.Utils;
using Newtonsoft.Json;
using UIKit;

namespace GroupExperiment
{
	public partial class DashboardController : UIViewController
	{
		public DashboardController (IntPtr handle) : base (handle)
		{
		}

        public string userName;
        public string accType;
        public string accNumber;
        public double accBalance;

        HttpClient client;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            userCardView.Layer.CornerRadius = 8;
            MyUtils.AddShadow(userCardView);

            userNameLabel.Text = "Hi, " + Commonclass.ActiveAccount.FirstName + "!";
            accTypeLabel.Text = Commonclass.ActiveAccount.AccountType;
            accNumberLabel.Text = Commonclass.ActiveAccount.AccountNumber;
            accBalanceLabel.Text = "₦" + Commonclass.ActiveAccount.AccountBalance.ToString("N0");

            GetBanks().Wait(200);

        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            NavigationController.NavigationBarHidden = true;
        }

        public async Task GetBanks()
        {
            client = new HttpClient(MyUtils.GetInsecureHandler());

            string url = "https://localhost:5001/Bank/get_banks";
            string url2 = "https://xmtapi.azurewebsites.net/Bank/get_banks";

            HttpResponseMessage response = await client.GetAsync(url);

            var responseAsString = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                Console.WriteLine(responseAsString);
                
                var banks = JsonConvert.DeserializeObject<string[]>(responseAsString);

                foreach (string bank in banks)
                {
                    Commonclass.Banks.Add(bank);
                    Console.WriteLine(bank);
                }
            }
            else
            { 
                Console.WriteLine(responseAsString);
            }
        }
    }
}
