// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GroupExperiment
{
	public partial class DashboardController : UIViewController
	{
		public DashboardController (IntPtr handle) : base (handle)
		{
		}

        public string userName;

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            userCardView.Layer.CornerRadius = 8;
            userCardView.ClipsToBounds = true;

            userNameLabel.Text = "Hi, " + userName + "!";

        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            NavigationController.NavigationBarHidden = true;
        }
    }
}
