// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace GroupExperiment
{
	public partial class SuccessStatusController : UIViewController
	{
		public SuccessStatusController (IntPtr handle) : base (handle)
		{
		}
	}
}
