// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GroupExperiment.Modules;
using UIKit;

namespace GroupExperiment
{
	public partial class SummaryController : UIViewController
	{
        public string groupName;
        public string numOfRecipients;
        public double totalAmount;

        MyAlerts alerter = new MyAlerts();

		public SummaryController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            Title = "Summary";

            groupSummaryCard.Layer.CornerRadius = 8;
            senderSummaryCard.Layer.CornerRadius = 8;
            senderSummaryCard.ClipsToBounds = true;

            groupNameLabel.Text = groupName;
            recipientsNumberLabel.Text = numOfRecipients;
            totalAmountLabel.Text = "₦" + totalAmount.ToString("0.###");

            confirmBtn.TouchUpInside += ConfirmBtn_TouchUpInside;
        }

        private void ConfirmBtn_TouchUpInside(object sender, EventArgs e)
        {
            alerter.ShowAlertWithTextField("Authentication", "Enter your pin", this, (UIAlertAction obj) =>
            {
                PerformSegue("toStatus",null);
            });
        }
    }
}
